name: Tests
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "src/cooklang_py/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "src/cooklang_py/**"
      - "tests/**"
      - "pyproject.toml"
jobs:
  test-against-python-matrix:
    name: PyTest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14", "3.15"]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Run tests
        run: |
          uv run -p ${{ matrix.python-version }} pytest
